// <auto-generated />
using System;
using Cosa_Cristina_Proiect.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Cosa_Cristina_Proiect.Migrations
{
    [DbContext(typeof(Cosa_Cristina_ProiectContext))]
    partial class Cosa_Cristina_ProiectContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Cosa_Cristina_Proiect.Models.Client", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumarTelefon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeClient")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Oras")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("Cosa_Cristina_Proiect.Models.Oferta", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("EuroCredit")
                        .HasColumnType("decimal(6, 2)");

                    b.Property<string>("NumeOferta")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Oferta");
                });

            modelBuilder.Entity("Cosa_Cristina_Proiect.Models.OfertaReincarcare", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("OfertaID")
                        .HasColumnType("int");

                    b.Property<int>("ReincarcareID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("OfertaID");

                    b.HasIndex("ReincarcareID");

                    b.ToTable("OfertaReincarcare");
                });

            modelBuilder.Entity("Cosa_Cristina_Proiect.Models.Reincarcare", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClientID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Numar")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ClientID");

                    b.ToTable("Reincarcare");
                });

            modelBuilder.Entity("Cosa_Cristina_Proiect.Models.OfertaReincarcare", b =>
                {
                    b.HasOne("Cosa_Cristina_Proiect.Models.Oferta", "Oferta")
                        .WithMany("OferteReincarcare")
                        .HasForeignKey("OfertaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cosa_Cristina_Proiect.Models.Reincarcare", "Reincarcare")
                        .WithMany("OferteReincarcare")
                        .HasForeignKey("ReincarcareID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cosa_Cristina_Proiect.Models.Reincarcare", b =>
                {
                    b.HasOne("Cosa_Cristina_Proiect.Models.Client", "Client")
                        .WithMany("Reincarcari")
                        .HasForeignKey("ClientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
